project/views/view_rate.py
"""View do Dashboard de avaliações da aplicação."""

from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from sqlalchemy import or_

from project.configs.server import server
from project.forms.form_rate import RateForm, SearchForm
from project.models.model_rate import RatingModel, TypeRate
from project.utils.upload import image_remove_and_upload, image_upload

db = server.db

ratebp = Blueprint(
    "ratebp",
    __name__,
)


@ratebp.route("/dashboard", methods=["GET"])
@login_required
def dashboard() -> Response:
    """View de Controle e Exibição do Dashboard, com dados do usuários, lista de avaliações e paginação.

    Decorators:
        @Login_required
        methods=["GET"]

    Returns:
        template: Dashboard
    """
    rates = RatingModel.query.filter_by(rater_id=current_user.id).order_by(
        RatingModel.date_posted.desc()
    )
    page = request.args.get("page", 1, type=int)
    rates_page = rates.paginate(page=page, per_page=10)
    return render_template("rate/dashboard.html", rates_page=rates_page)


@ratebp.route("/create", methods=["GET", "POST"])
@login_required
def create() -> Response:
    """View de Controle e Criação de Avaliação, com gestão de upload de imagem.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Returns:
        template: Dashboard | Create
    """
    form = RateForm()
    if form.validate_on_submit():
        try:
            # verify if rate_type exists on Enum class
            type_rate = TypeRate(form.rate_type.data).name
        except:
            type_rate = "ANIME"
            flash("Wrong Type Selected! :(, ANIME selected", category="danger")
        finally:
            rate_pic = image_upload(request.files["rate_pic"])
            new_rate = RatingModel(
                title=form.title.data,
                content=form.content.data,
                rate=int(form.rate.data),
                rater_id=current_user.id,
                rate_pic=rate_pic,
                rate_type=type_rate,
            )

            try:
                db.session.add(new_rate)
                db.session.commit()
                flash("Rate added successfully!", category="success")
                return redirect(url_for("ratebp.dashboard"))
            except:
                flash("Error with database", category="danger")
    return render_template("rate/create_rate.html", form=form)


@ratebp.route("/update/<int:id>", methods=["GET", "POST"])
@login_required
def update(id: int) -> Response:
    """View de Controle e atualização de Avaliação.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Args:
        id (int): O identificador da avaliação a ser atualizada

    Returns:
        Response: Dashboard | Update
    """
    rate = RatingModel.query.get_or_404(id)
    form = RateForm(obj=rate)  # preselect that rate_type
    if current_user.id == rate.rater_id:
        if form.validate_on_submit():
            rate.title = form.title.data
            rate.content = form.content.data
            rate.rate = form.rate.data
            try:
                rate.rate_type = TypeRate(form.rate_type.data).name
                try:
                    db.session.add(rate)
                    db.session.commit()
                    flash("Rate Updated successfully!", category="success")
                    return redirect(url_for("ratebp.dashboard"))
                except:
                    flash("Error with database", category="danger")
                    return redirect(url_for("ratebp.update", id=id))
            except:
                flash("Wrong Type Selected! :(", category="danger")
                return redirect(url_for("ratebp.update", id=id))
        # Rate type conversion
        form.rate_type.data = rate.rate_type.value
        return render_template("rate/update_rate.html", form=form, rate=rate)
    else:
        flash("You bot allowed to edit that rate!", category="warning")
        return redirect(url_for("ratebp.dashboard"))


@ratebp.route("/delete/<int:id>", methods=["GET"])
@login_required
def delete(id: int) -> Response:
    """View de Controle e Remoção de Avaliação.

    Decorators:
        @Login_required
        methods=["GET"]

    Args:
        id (int): O identificador da avaliação a ser removida

    Returns:
        Response: Dashboard
    """
    rate = RatingModel.query.get_or_404(id)
    if current_user.id == rate.rater.id:
        try:
            db.session.delete(rate)
            db.session.commit()
            flash("Rate Was Deletd!")
        except:
            flash("Error to deleting the rate...")
        finally:
            return redirect(url_for("ratebp.dashboard"))
    else:
        flash("You cannot delete this post")
        return redirect(url_for("ratebp.dashboard"))


@ratebp.route("/read/<int:id>", methods=["GET"])
@login_required
def read(id: int) -> Response:
    """View de Controle e Leitura de Avaliação.

    Decorators:
        @Login_required
        methods=["GET"]

    Args:
        id (int): O identificador da avaliação a ser visualizada

    Returns:
        Response: Dashboard
    """
    rate = RatingModel.query.get_or_404(id)
    return render_template("rate/read_rate.html", rate=rate)


@ratebp.route("/search", methods=["POST"])
@login_required
def search() -> Response:
    """View de Controle e Pesquisa de Avaliação.

    Decorators:
        @Login_required
        methods=["POST"]

    Returns:
        Response: Result
    """
    form = SearchForm()
    rating = RatingModel.query
    if form.validate_on_submit():
        search = form.search.data

        title_query = RatingModel.title.like("%" + search + "%")
        type_rate_query = RatingModel.rate_type.like("%" + search + "%")

        rating = rating.filter(or_(title_query, type_rate_query))
        rating = rating.order_by(RatingModel.date_posted).all()
        return render_template("rate/search_result.html", search=search, rating=rating)
    else:
        flash("Error :(", category="danger")
        return redirect(url_for("ratebp.dashboard"))

project/views/view_user.py
"""View dos controle de cadastro e login de Usuários."""

import os
import uuid as uuid
from typing import Union

from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import (
    LoginManager,
    current_user,
    login_required,
    login_user,
    logout_user,
)
from werkzeug.utils import secure_filename

from project.configs.server import server
from project.forms.form_user import LoginForm, UpdateForm, UpdatePicForm, UserForm
from project.models.model_user import UsersModel
from project.utils.upload import image_remove_and_upload, image_upload

db = server.db

userbp = Blueprint(
    "userbp",
    __name__,
)


@userbp.route("/login", methods=["GET", "POST"])
def login() -> Response:
    """View de controle de login do usuário.

    Decorators:
        methods=["GET", "POST"]

    Returns:
        Union[Response, str]: Dashboard | Index
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = UsersModel.query.filter_by(username=form.username.data).first()
        if user:  # If username exists
            if user.verify_password(
                form.password.data
            ):  # verify if user use correct pw
                remember = (
                    True if form.remember.data else False
                )  # verify if remember is select
                login_user(user, remember=remember)  # login that user
                return redirect(url_for("ratebp.dashboard"))
            else:
                logout_user()
                flash("Wrong Username or Password - Try Again!", category="warning")
        else:
            logout_user()
            flash("That User do not exists - Try Again!", category="warning")
    return render_template("user/login.html", form=form)


@userbp.route("/logout", methods=["GET", "POST"])
def logout() -> Response:
    """View de controle de logout do usuário.

    Decorators:
        methods=["GET", "POST"]

    Returns:
        Response: Login
    """
    logout_user()  # logout current user
    flash("Logout!", category="success")
    return redirect(url_for("userbp.login"))


@userbp.route("/register", methods=["GET", "POST"])
def register() -> Response:
    """View de controle de cadastro de um novo usuário.

    Decorators:
        methods=["GET", "POST"]

    Returns:
        Union[Response, str]: Login | Register
    """
    form = UserForm()
    if not current_user.is_authenticated:
        if form.validate_on_submit():  # Verify form fields
            email = UsersModel().query.filter_by(email=form.email.data).first()
            username = UsersModel().query.filter_by(email=form.email.data).first()
            if (username is None) and (email is None):
                new_user = UsersModel(
                    username=form.username.data,
                    email=form.email.data,
                    password=form.password.data,
                )

                try:  # Save in Database
                    db.session.add(new_user)
                    db.session.commit()
                    flash("User added Successfully", category="success")
                    return redirect(url_for("userbp.login"))
                except:
                    flash("error with Database :)", category="danger")
                    return redirect(url_for("userbp.register"))
            else:
                flash("Username or email Already Exists", category="info")
            # Clear the form
            form.password.data = ""

        return render_template("user/register.html", form=form)
    else:
        return redirect(url_for("ratebp.dashboard"))


@userbp.route("/update", methods=["GET", "POST"])
@login_required
def update() -> Response:
    """Vire de controle de atualização do usuário atual da aplicação.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Returns:
        Union[Response, str]: Dashboard | Update
    """
    id = current_user.id
    user = UsersModel.query.get_or_404(id)  # get current user if exists
    form = UpdateForm(obj=user)
    if form.validate_on_submit():
        user.name = request.form["name"]
        user.username = request.form["username"]
        user.about = request.form["about"]
        try:
            db.session.add(user)
            db.session.commit()
            flash("User Updated Successfully", category="success")
            return redirect(url_for("ratebp.dashboard"))
        except:
            flash("Error with database", category="danger")
            return redirect(url_for("userbp.update"))
    else:
        user.name = user.name if user.name else ""
        return render_template("user/update.html", form=form, user=user)


@userbp.route("/update/pic", methods=["GET", "POST"])
@login_required
def pic_update() -> Response:
    """View de controle de atualização da foto de perfil do usuário atual.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Returns:
        Union[Response, str]: Dashboard | UpdatePic
    """
    form = UpdatePicForm()
    id = current_user.id
    user = UsersModel.query.get_or_404(id)
    if request.method == "POST":
        new_profile_pic = image_remove_and_upload(
            request.files["profile_pic"], user.profile_pic
        )
        user.profile_pic = new_profile_pic
        try:
            db.session.add(user)
            db.session.commit()
            flash("Picture Updated Successfully", category="success")
            return redirect(url_for("ratebp.dashboard"))
        except:
            flash("Error with database", category="danger")
            return redirect(url_for("userbp.pic_update"))
    else:
        return render_template("user/pic_update.html", form=form, user=user)

project/templates/base.html
<!doctype html>
<html lang="en">

  <head>
    <title>{% block title %}Bem-vindo{% endblock title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/f6213ee45f.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

  </head>

  <body class="bg-dark text-white h-100 w-100">

    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container">
          <a class="navbar-brand" href="{{ url_for('index') }}">HOME</a>
          <button class="navbar-toggler hidden-lg-up" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"></button>
          <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav me-auto mt-2 mt-lg-0">
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('ratebp.dashboard') }}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('userbp.logout') }}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('userbp.login') }}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('userbp.register') }}">Register</a>
              </li>
              {% endif %}
            </ul>
            {% if current_user.is_authenticated %}
            <form class="d-flex my-2 my-lg-0" action="{{url_for('ratebp.search')}}" method="POST">
              {{search_form.hidden_tag()}}
              {{search_form.search(class="form-control me-sm-2", placeholder="Search")}}

              {{search_form.submit(class="btn btn-outline-success my-2 my-sm-0")}}
            </form>
            {% endif %}
          </div>
        </div>
      </nav>
      <br>

      <div class="">
        {% block content %}{% endblock content %}
      </div>

    </div>


    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>

</html>

project/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="p-5 bg-gradient">
  <h1 class="display-3"> RatingStars</h1>
  <p class="lead">Personal study project about flask and python.</p>
  <hr class="my-2">
  <h2 class="display-4">Learned Skills</h2>
  <ul>
    <li>Python</li>
    <li>GitFlow</li>
    <li>Heroku</li>
    <li>Flask</li>
    <li>Flask-Admin</li>
    <li>Flask-CKEditor</li>
    <li>Flask-Login</li>
    <li>Flask-Migrate</li>
    <li>Flask-SQLAlchemy</li>
    <li>Flask-WTF</li>
  </ul>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="https://github.com/adrianomqsmts/blog-flask" role="button">Github Repository</a>
  </p>
</div>
{% endblock content %}