project/views/view_rate.py
"""View do Dashboard de avaliações da aplicação."""

from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from sqlalchemy import or_

from project.configs.server import server
from project.forms.form_rate import RateForm, SearchForm
from project.models.model_rate import RatingModel, TypeRate
from project.utils.upload import image_remove_and_upload, image_upload

db = server.db

ratebp = Blueprint(
    "ratebp",
    __name__,
)


@ratebp.route("/dashboard", methods=["GET"])
@login_required
def dashboard() -> Response:
    """View de Controle e Exibição do Dashboard, com dados do usuários, lista de avaliações e paginação.

    Decorators:
        @Login_required
        methods=["GET"]

    Returns:
        template: Dashboard
    """
    rates = RatingModel.query.filter_by(rater_id=current_user.id).order_by(
        RatingModel.date_posted.desc()
    )
    page = request.args.get("page", 1, type=int)
    rates_page = rates.paginate(page=page, per_page=10)
    return render_template("rate/dashboard.html", rates_page=rates_page)


@ratebp.route("/create", methods=["GET", "POST"])
@login_required
def create() -> Response:
    """View de Controle e Criação de Avaliação, com gestão de upload de imagem.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Returns:
        template: Dashboard | Create
    """
    form = RateForm()
    if form.validate_on_submit():
        try:
            # verify if rate_type exists on Enum class
            type_rate = TypeRate(form.rate_type.data).name
        except:
            type_rate = "ANIME"
            flash("Wrong Type Selected! :(, ANIME selected", category="danger")
        finally:
            rate_pic = image_upload(request.files["rate_pic"])
            new_rate = RatingModel(
                title=form.title.data,
                content=form.content.data,
                rate=int(form.rate.data),
                rater_id=current_user.id,
                rate_pic=rate_pic,
                rate_type=type_rate,
            )

            try:
                db.session.add(new_rate)
                db.session.commit()
                flash("Rate added successfully!", category="success")
                return redirect(url_for("ratebp.dashboard"))
            except:
                flash("Error with database", category="danger")
    return render_template("rate/create_rate.html", form=form)


@ratebp.route("/update/<int:id>", methods=["GET", "POST"])
@login_required
def update(id: int) -> Response:
    """View de Controle e atualização de Avaliação.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Args:
        id (int): O identificador da avaliação a ser atualizada

    Returns:
        Response: Dashboard | Update
    """
    rate = RatingModel.query.get_or_404(id)
    form = RateForm(obj=rate)  # preselect that rate_type
    if current_user.id == rate.rater_id:
        if form.validate_on_submit():
            rate.title = form.title.data
            rate.content = form.content.data
            rate.rate = form.rate.data
            try:
                rate.rate_type = TypeRate(form.rate_type.data).name
                try:
                    db.session.add(rate)
                    db.session.commit()
                    flash("Rate Updated successfully!", category="success")
                    return redirect(url_for("ratebp.dashboard"))
                except:
                    flash("Error with database", category="danger")
                    return redirect(url_for("ratebp.update", id=id))
            except:
                flash("Wrong Type Selected! :(", category="danger")
                return redirect(url_for("ratebp.update", id=id))
        # Rate type conversion
        form.rate_type.data = rate.rate_type.value
        return render_template("rate/update_rate.html", form=form, rate=rate)
    else:
        flash("You bot allowed to edit that rate!", category="warning")
        return redirect(url_for("ratebp.dashboard"))


@ratebp.route("/delete/<int:id>", methods=["GET"])
@login_required
def delete(id: int) -> Response:
    """View de Controle e Remoção de Avaliação.

    Decorators:
        @Login_required
        methods=["GET"]

    Args:
        id (int): O identificador da avaliação a ser removida

    Returns:
        Response: Dashboard
    """
    rate = RatingModel.query.get_or_404(id)
    if current_user.id == rate.rater.id:
        try:
            db.session.delete(rate)
            db.session.commit()
            flash("Rate Was Deletd!")
        except:
            flash("Error to deleting the rate...")
        finally:
            return redirect(url_for("ratebp.dashboard"))
    else:
        flash("You cannot delete this post")
        return redirect(url_for("ratebp.dashboard"))


@ratebp.route("/read/<int:id>", methods=["GET"])
@login_required
def read(id: int) -> Response:
    """View de Controle e Leitura de Avaliação.

    Decorators:
        @Login_required
        methods=["GET"]

    Args:
        id (int): O identificador da avaliação a ser visualizada

    Returns:
        Response: Dashboard
    """
    rate = RatingModel.query.get_or_404(id)
    return render_template("rate/read_rate.html", rate=rate)


@ratebp.route("/search", methods=["POST"])
@login_required
def search() -> Response:
    """View de Controle e Pesquisa de Avaliação.

    Decorators:
        @Login_required
        methods=["POST"]

    Returns:
        Response: Result
    """
    form = SearchForm()
    rating = RatingModel.query
    if form.validate_on_submit():
        search = form.search.data

        title_query = RatingModel.title.like("%" + search + "%")
        type_rate_query = RatingModel.rate_type.like("%" + search + "%")

        rating = rating.filter(or_(title_query, type_rate_query))
        rating = rating.order_by(RatingModel.date_posted).all()
        return render_template("rate/search_result.html", search=search, rating=rating)
    else:
        flash("Error :(", category="danger")
        return redirect(url_for("ratebp.dashboard"))

project/views/view_season.py
"""View do da avaliação por temporadas de uma dada avaliação única."""

from typing import Union

from flask import (
    Blueprint,
    Response,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required

from project.configs.server import server
from project.forms.form_season import SeasonForm
from project.models.model_rate import RatingModel
from project.models.model_season import SeasonModel
from project.utils.upload import image_remove_and_upload, image_upload

db = server.db

seasonbp = Blueprint(
    "seasonbp",
    __name__,
)


@seasonbp.route("/create/<int:id>", methods=["GET", "POST"])
@login_required
def create(id: int) -> Response:
    """View de controle e criação de uma avaliação de temporada.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Args:
        id (int): Identificador da avaliação que será inserida uma nova temporada

    Returns:
        Union[Response, str]: Dashboard | Create | 404
    """
    form = SeasonForm()
    rate = RatingModel.query.get_or_404(id)
    if rate.rater_id == current_user.id:
        if form.validate_on_submit():
            season_pic = image_upload(request.files["season_pic"])
            new_season = SeasonModel(
                season=int(form.season.data),
                title=form.title.data,
                season_pic=season_pic,
                content=form.content.data,
                rate=form.rate.data,
                rate_id=rate.id,
            )
            try:
                db.session.add(new_season)
                db.session.commit()
            except:
                flash("Erro with database", category="danger")
                return redirect(url_for("sessionbp.create"))
            flash("Season Rating Created Successfully", category="success")
            return redirect(url_for("ratebp.read", id=id))
        return render_template("season/create_season.html", form=form)
    else:
        flash(
            "You Cannot Create a new Rate Season on that Rate. database",
            category="warning",
        )
        return redirect(url_for("ratebp.dashboard"))


@seasonbp.route("/update/<int:id>", methods=["GET", "POST"])
@login_required
def update(id: int) -> Response:
    """View de controle e criação de uma avaliação de temporada.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Args:
        id (int): Identificador da temporada que será atualizada.

    Returns:
        Union[Response, str]: Dashboard | Update | 404
    """
    season = SeasonModel.query.get_or_404(id)
    form = SeasonForm(
        rate=season.rate,
        title=season.title,
        season=season.season,
        content=season.content,
    )
    if current_user.id == season.seasons.rater_id:
        if form.validate_on_submit():

            season.rate = form.rate.data
            season.title = form.title.data
            season.season = form.season.data
            season.content = form.content.data

            try:
                db.session.add(season)
                db.session.commit()
            except:
                flash("Error with database", category="danger")
                return redirect(url_for("seasonbp.update", id=id))
            flash("Rate Updated successfully!", category="success")
            return redirect(url_for("ratebp.read", id=season.rate_id))
        form.rate.default = season.rate
        return render_template("season/update_season.html", form=form, season=season)
    else:
        flash("You bot allowed to edit that rate!", category="warning")
        return redirect(url_for("ratebp.dashboard"))


@seasonbp.route("/delete/<int:id>")
@login_required
def delete(id: int) -> Response:
    """View de controle e remoção de uma avaliação de temporada.

    Decorators:
        @Login_required
        methods=["GET", "POST"]

    Args:
        id (int): Identificador da temporada que será removida.

    Returns:
        Response: Dashboard
    """
    season = SeasonModel.query.get_or_404(id)
    if current_user.id == season.seasons.rater_id:
        try:
            db.session.delete(season)
            db.session.commit()
            flash("season Was Deleted!")
        except:
            flash("Error to deleting the season...")
        finally:
            return redirect(url_for("ratebp.read", id=season.rate_id))
    else:
        flash("You cannot delete this post")
        return redirect(url_for("ratebp.read", id=season.rate_id))

project/templates/rate/create_rate.html
{% extends 'base.html' %}

{% block title %}New Rate{% endblock title %}

{% block content %}

{% for category, message in get_flashed_messages(with_categories=True) %}
<div
  class="alert alert-{{ 'primary' if category=='message' else category if category else 'primary' }} alert-dismissible fade show"
  role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <strong>{{message}}</strong>
</div>
{% endfor %}

<div class="div-center2">
  <div class="login-form">
    <div class="card text-start">
      <div class="card-body text-dark">
        <a name="voltar" class="btn btn-outline-secondary" href="{{ url_for('ratebp.dashboard') }}" role="button">Voltar</a>
        <h4 class="card-title text-center">Rate</h4>
        <hr>
        <form action="" method="POST" enctype="multipart/form-data">
          {{form.hidden_tag()}}
          {{form.title.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.title.errors[0]}}
          </span>
          {{form.title(class="form-control")}}

          {{form.rate_type.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.rate_type.errors[0]}}
          </span>
          {{form.rate_type(class="form-control")}}

          {{form.rate_pic.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.rate_pic.errors[0]}}
          </span>
          {{form.rate_pic(class="form-control")}}

          {{form.content.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.content.errors[0]}}
          </span>
          {{form.content(class="form-control")}}
          <br>
          {{form.rate.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.rate.errors[0]}}
          </span>
          <div class="container">
            <div class="starrating risingstar d-flex justify-content-center flex-row-reverse">
              {% for subfield in form.rate %}
              {% if subfield.data == 1 %}
              {{ subfield(checked=True) }}
              {{ subfield.label }}
              {% else %}
              {{ subfield }}
              {{ subfield.label }}
              {% endif %}
              {% endfor %}
            </div>
          </div>

          <br> <br>
          {{form.submit(class="btn btn-primary w-100")}}

        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name = 'content', showWordCount = True) }}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

project/templates/rate/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}

{% for category, message in get_flashed_messages(with_categories=True) %}
<div
  class="alert alert-{{ 'primary' if category=='message' else category if category else 'primary' }} alert-dismissible fade show"
  role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <strong>{{message}}</strong>
</div>
{% endfor %}
<div class="card border-primary text-dark">
  <div class="card-body">
    <div class='container'>
      <div class='row'>
        <div class='col-2'>
          <div id="wrapper">
            <img class="img-fluid profile-pic rounded-circle border-dark"
              src="{{ url_for('static', filename='images/' + (current_user.profile_pic if current_user.profile_pic else 'profile.png')) }}"
              alt="Profile Pic">
            <a href="{{ url_for('userbp.pic_update') }}" class="a-text">
              <div class="text text-center center h-100 w-100">Update Image</div>
            </a>
          </div>
          </a>
        </div>
        <div class='col-8'>
          <p class="card-title text-center">
            {% if current_user.name %}
            <span class="h4">{{current_user.name|title}}</span>
            {% endif %}
            </pan class='h4'>@{{current_user.username|upper}}</span>
          <p>
          <p class="text-justify">
            {% if current_user.about %}
            {{ current_user.about|safe}}
            {% else %}
          <p class="lead">About . . . .</p>
          {% endif %}
          </p>
        </div>
        <div class='col-2 text-right'>
          <a href="{{ url_for('userbp.update') }}" class="btn btn-primary w-100"><i class="fas fa-edit"></i></a>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="center pb-3">
    <a class="btn w-100 text-center  btn-outline-primary" href="{{ url_for('ratebp.create') }}" role="button">New
      Rate</a>
  </div>
  <br>
  <br>
</div>

<hr>
<div class="row">
  {% for rate in rates_page.items %}
  <div class="col-md-6 pb-4 d-flex">
    <div class="card flex-fill text-dark">
      <div class="card-header">
        <div class="d-flex flex-row-reverse">
          <span>
            {% for i in range(rate.rate) %}
            <span class="fa fa-star checked"></span>
            {% endfor %}
            {% for i in range(5-rate.rate) %}
            <span class="fa fa-star"></span>
            {% endfor %} | {{ rate.rate_type.value }} | {{rate.date_posted.strftime('%Y-%m-%d')}}
          </span>
        </div>
      </div>
      <div class="card-body d-flex flex-column">
        <div class="card-title h3 text-center">
          <a class="text-decoration-none text-dark" href="{{ url_for('ratebp.read', id=rate.id) }}">
            <img class=" card-img-top img-fluid rate-pic-card"
              src="{{ url_for('static', filename='images/' + (rate.rate_pic if rate.rate_pic else 'star.png')) }}"
              alt="Rate Pic">

            {{rate.title}}
          </a>
        </div>
        <hr>
        <div class="card-text h-100">
          <p class="text-break">{{rate.content|safe}}</p>
        </div>
        <div class="card-footer m-auto d-flex flex-row-reverse w-100">
          <a href="{{ url_for('ratebp.update', id=rate.id) }}" class="btn btn-primary"><i
              class="fas fa-edit"></i></a>
          <a href="{{ url_for('ratebp.delete', id=rate.id) }}" class="btn btn-danger"><i
              class="far fa-trash-alt"></i></a>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
</div>

<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    <li class="page-item {% if rates_page.page == 1 %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for('ratebp.dashboard', page=rates_page.prev_num) }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="visually-hidden">Previous</span>
      </a>
    </li>
    {% for page in range(rates_page.pages) %}
    <li class="page-item {% if rates_page.page == (page+1) %}active{% endif %}">
      <a class="page-link" href="{{ url_for('ratebp.dashboard', page=(page+1)) }}">{{page+1}}</a>
    </li>
    {% endfor %}
    <li class="page-item {% if rates_page.page == rates_page.pages or rates_page.pages==0 %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for('ratebp.dashboard', page=rates_page.next_num) }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="visually-hidden">Next</span>
      </a>
    </li>
  </ul>
</nav>

{% endblock content %}

project/templates/rate/rate.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}

{% for category, message in get_flashed_messages(with_categories=True) %}
<div class="alert alert-{{ 'primary' if category=='message' else category if category else 'primary' }} alert-dismissible fade show" role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <strong>{{message}}</strong>
</div>
{% endfor %}

<div class="div-center2">
  <div class="login-form">
    <div class="card text-start">
      <div class="card-body text-dark">
        <h4 class="card-title text-center">Rate</h4>
        <hr>
        <form action="" method="POST">
          {{form.hidden_tag()}}
          {{form.title.label(class="form-label")}}:
          {{form.title(class="form-control")}}

          {{form.original_title.label(class="form-label")}}:
          {{form.original_title(class="form-control")}}

          {{form.content.label(class="form-label")}}:
          {{form.content(class="form-control")}}
          <br>
          {{form.rate.label(class="form-label")}}: 
          <div class="container">
            <div class="starrating risingstar d-flex justify-content-center flex-row-reverse">
              {% for subfield in form.rate %}

              {{ subfield }}
              {{ subfield.label }}

              {% endfor %}
            </div>
          </div>
          <br> <br>
          {{form.submit(class="btn btn-primary w-100")}}
        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name = 'content', showWordCount = True) }}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

project/templates/rate/read_rate.html
{% extends 'base.html' %}

{% block title %}Read Rate{% endblock title %}

{% block content %}

{% for category, message in get_flashed_messages(with_categories=True) %}
<div
  class="alert alert-{{ 'primary' if category=='message' else category if category else 'primary' }} alert-dismissible fade show"
  role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <strong>{{message}}</strong>
</div>
{% endfor %}

<div class="card text-start text-dark mb-2">
  <div class="card-body">
    <div class="row w-100">
      <div class="col-10">
        <h4 class="card-title"><a href="{{ url_for('ratebp.read', id=rate.id) }}">{{rate.title}}</a></h4>
      </div>
      {% if current_user.id == rate.rater_id %}
      <div class="col-2 d-flex">
        <a name="voltar" class="btn btn-outline-secondary" href="{{ url_for('ratebp.dashboard') }}" role="button">Voltar</a>
        <a href="{{ url_for('ratebp.update', id=rate.id) }}" class="w-50 btn btn-primary"><i
            class="fas fa-edit"></i></a>
        <a href="{{ url_for('ratebp.delete', id=rate.id) }}" class="w-50 btn btn-danger"><i
            class="far fa-trash-alt"></i></a>
      </div>
      {% endif %}
    </div>
    <p class="card-text">
      {% for i in range(rate.rate) %}
      <span class="fa fa-star checked"></span>
      {% endfor %}
      {% for i in range(5-rate.rate) %}
      <span class="fa fa-star"></span>
      {% endfor %} | {{ rate.rate_type.value }} | {{rate.date_posted.strftime('%Y-%m-%d')}}
    </p>
    <hr>
    <div class="row">
      <div class="col-2">
        <img class="img-fluid profile-pic border-dark"
          src="{{ url_for('static', filename='images/' + (rate.rate_pic if rate.rate_pic else 'star.png')) }}"
          alt="Rate Pic">
      </div>
      <div class="col-10">
        <p class="card-text">{{rate.content|safe}}</p>
      </div>
    </div>
    <div class="center">
      <a class="btn w-100 text-center  btn-outline-primary" href="{{ url_for('seasonbp.create', id=rate.id) }}"
        role="button">New Season Rate</a>
    </div>
  </div>
</div>



<hr>

{% for season in rate.seasons %}
<div class="card text-start text-dark mb-2">
  <div class="card-body">
    <div class="row w-100">
      <div class="col-10">
        <h4 class="card-title">{{season.title}} {{season.season}}</h4>
      </div>
      <div class="col-2 d-flex">
        <a href="{{ url_for('seasonbp.update', id=season.id) }}" class="w-50 btn btn-primary"><i
            class="fas fa-edit"></i></a>
        <a href="{{ url_for('seasonbp.delete', id=season.id) }}" class="w-50 btn btn-danger"><i
            class="far fa-trash-alt"></i></a>
      </div>
    </div>
    <p class="card-text">
      {% for i in range(season.rate) %}
      <span class="fa fa-star checked"></span>
      {% endfor %}
      {% for i in range(5-season.rate) %}
      <span class="fa fa-star"></span>
      {% endfor %} | {{season.date_posted.strftime('%Y-%m-%d')}}
    </p>
    <hr>
    <div class="row">
      <div class="col-2">
        <img class="img-fluid profile-pic border-dark "
          src="{{ url_for('static', filename='images/' + (season.season_pic if season.season_pic else 'star.png')) }}"
          alt="season Pic">
      </div>

      <div class="col-10">
        <p class="card-text">{{season.content|safe}}</p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

project/templates/rate/search_result.html
{% extends 'base.html' %}

{% block title %}Search{% endblock title %}

{% block content %}

{% for category, message in get_flashed_messages(with_categories=True) %}
<div
  class="alert alert-{{ 'primary' if category=='message' else category if category else 'primary' }} alert-dismissible fade show"
  role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <strong>{{message}}</strong>
</div>
{% endfor %}

<div class="card text-center text-dark">
  <div class="card-body">
    <a name="voltar" class="btn btn-outline-secondary" onclick="history.back(-1)" role="button">Voltar</a>
    <h4 class="card-title">Search results for: <span class="text-muted">{{search}}</span></h4>
  </div>
</div>

<hr>

{% for rate in rating %}
<div class="card text-start text-dark mb-2">
  <div class="card-body">
    <div class="row w-100">
      <div class="col-10">
        <h4 class="card-title">
          {% if current_user.id == rate.rater_id %}
          <a href="{{ url_for('ratebp.read', id=rate.id) }}">{{rate.title}}</a>
          {% else %}
          {{rate.title}}
          {% endif %}
        </h4>
      </div>
      <div class="col-2 d-flex">
        {% if current_user.id == rate.rater_id %}
        <a href="{{ url_for('ratebp.update', id=rate.id) }}" class="w-50 btn btn-primary"><i
            class="fas fa-edit"></i></a>
        <a href="{{ url_for('ratebp.delete', id=rate.id) }}" class="w-50 btn btn-danger"><i
            class="far fa-trash-alt"></i></a>

        {% endif %}

      </div>
    </div>
    <p class="card-text">
      {% for i in range(rate.rate) %}
      <span class="fa fa-star checked"></span>
      {% endfor %}
      {% for i in range(5-rate.rate) %}
      <span class="fa fa-star"></span>
      {% endfor %} | {{ rate.rate_type.value }} | rated by: {{rate.rater.username}} | at
      {{rate.date_posted.strftime('%Y-%m-%d')}}
    </p>
    <hr>
    <div class="row">
      <div class="col-2">
        <img class="img-fluid rate-pic border-dark"
          src="{{ url_for('static', filename='images/' + (rate.rate_pic if rate.rate_pic else 'star.png')) }}"
          alt="Rate Pic">

      </div>
      <div class="col-10">
        <p class="card-text">{{rate.content|safe}}</p>
      </div>
    </div>
  </div>
</div>
{% endfor %}


{% endblock content %}

project/templates/rate/update_rate.html
{% extends 'base.html' %}

{% block title %}Update Rate{% endblock title %}

{% block content %}

{% for category, message in get_flashed_messages(with_categories=True) %}
<div
  class="alert alert-{{ 'primary' if category=='message' else category if category else 'primary' }} alert-dismissible fade show"
  role="alert">
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  <strong>{{message}}</strong>
</div>
{% endfor %}

<div class="div-center2">
  <div class="login-form">
    <div class="card text-start">
      <div class="card-body text-dark">
        <a name="voltar" class="btn btn-outline-secondary" href="{{ url_for('ratebp.dashboard') }}" role="button">Voltar</a>
        <h4 class="card-title text-center">Rate</h4>
        <hr>
        <form action="" method="POST">
          {{form.hidden_tag()}}
          {{form.title.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.title.errors[0]}}
          </span>
          {{form.title(class="form-control")}}

          {{form.rate_type.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.rate_type.errors[0]}}
          </span>
          {{form.rate_type(class="form-control")}}

          {{form.content.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.content.errors[0]}}
          </span>
          {{form.content(class="form-control")}}


          <br>
          {{form.rate.label(class="form-label")}}:
          <span class="form-text text-danger">
            {{form.rate.errors[0]}}
          </span>
          <div class="container">
            <div class="starrating risingstar d-flex justify-content-center flex-row-reverse">
              {% for subfield in form.rate %}
              {% if subfield.data == rate.rate %}
              {{ subfield(checked=True) }}
              {{ subfield.label }}
              {% else %}
              {{ subfield }}
              {{ subfield.label }}
              {% endif %}
              {% endfor %}
            </div>
          </div>
          <br> <br>
          {{form.submit(class="btn btn-primary w-100")}}
        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name = 'content', showWordCount = True) }}
      </div>
    </div>
  </div>
</div>
{% endblock content %}